# Generated by Django 5.0.1 on 2024-07-20 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac_terapeutico',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='comision',
        ),
        migrations.AddField(
            model_name='estilo',
            name='estilo',
            field=models.CharField(default='Sin estilo', max_length=50),
        ),
        migrations.AddField(
            model_name='estilo',
            name='horarios',
            field=models.CharField(default='Sin estilo', max_length=50),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='nombre',
            field=models.CharField(default='Sin estilo', max_length=50),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
