# Generated by Django 5.1 on 2024-08-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_remove_ac_terapeutico_pregunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('motivo', models.CharField(max_length=500)),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='ac_terapeutico',
        ),
    ]
