# Generated by Django 5.0.1 on 2024-07-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_remove_ac_terapeutico_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_terapeutico',
            name='asist_semanales',
            field=models.CharField(default='Sin estilo', max_length=50),
        ),
        migrations.AddField(
            model_name='ac_terapeutico',
            name='horario',
            field=models.CharField(default='Sin estilo', max_length=50),
        ),
        migrations.AlterField(
            model_name='ac_terapeutico',
            name='nombre',
            field=models.CharField(default='Sin estilo', max_length=60),
        ),
    ]
