# Generated by Django 5.0.1 on 2024-07-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_consulta_delete_ac_terapeutico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Ac_terapeutico',
            name='pregunta',
            field=models.CharField(default='Sin estilo', max_length=500),
        ),
    ]
