# Generated by Django 5.0.1 on 2024-07-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_ac_terapeutico_asist_semanales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='pregunta',
            field=models.CharField(default='Sin estilo', max_length=500),
        ),
    ]
