# Generated by Django 5.1 on 2024-08-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_consultas'),
    ]

    operations = [
        migrations.DeleteModel(
            
            name="consultas",
            
        ),
        migrations.RemoveField( 
            model_name="consultas",
            name="pregunta",
            
        )
    ]
