# Generated by Django 5.1 on 2024-08-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_delete_consultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ac_terapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(default='Sin estilo', max_length=60)),
                ('horario', models.CharField(default='Sin estilo', max_length=50)),
            ],
        ),
    ]
